package com.pyx.community.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.id
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.notifier
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.notifier_name
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.receiver
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.outerId
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.type
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.gmt_create
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.status
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.outerTitle
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    private String outertitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.id
     *
     * @return the value of t_notification.id
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.id
     *
     * @param id the value for t_notification.id
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.notifier
     *
     * @return the value of t_notification.notifier
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.notifier
     *
     * @param notifier the value for t_notification.notifier
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.notifier_name
     *
     * @return the value of t_notification.notifier_name
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.notifier_name
     *
     * @param notifierName the value for t_notification.notifier_name
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName == null ? null : notifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.receiver
     *
     * @return the value of t_notification.receiver
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.receiver
     *
     * @param receiver the value for t_notification.receiver
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.outerId
     *
     * @return the value of t_notification.outerId
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.outerId
     *
     * @param outerid the value for t_notification.outerId
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.type
     *
     * @return the value of t_notification.type
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.type
     *
     * @param type the value for t_notification.type
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.gmt_create
     *
     * @return the value of t_notification.gmt_create
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.gmt_create
     *
     * @param gmtCreate the value for t_notification.gmt_create
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.status
     *
     * @return the value of t_notification.status
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.status
     *
     * @param status the value for t_notification.status
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.outerTitle
     *
     * @return the value of t_notification.outerTitle
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public String getOutertitle() {
        return outertitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.outerTitle
     *
     * @param outertitle the value for t_notification.outerTitle
     *
     * @mbg.generated Sun Jul 19 17:42:26 CST 2020
     */
    public void setOutertitle(String outertitle) {
        this.outertitle = outertitle == null ? null : outertitle.trim();
    }
}